TRUNCATE TABLE users                    RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_roles               RESTART IDENTITY CASCADE;

TRUNCATE TABLE organizations            RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_orgs                RESTART IDENTITY CASCADE;

TRUNCATE TABLE projects                 RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_projects            RESTART IDENTITY CASCADE;
TRUNCATE TABLE project_settings         RESTART IDENTITY CASCADE;

TRUNCATE TABLE tasks                    RESTART IDENTITY CASCADE;
TRUNCATE TABLE sub_tasks                RESTART IDENTITY CASCADE;
TRUNCATE TABLE sub_tasks_done           RESTART IDENTITY CASCADE;

TRUNCATE TABLE stocks                   RESTART IDENTITY CASCADE;
TRUNCATE TABLE purchased_order          RESTART IDENTITY CASCADE;
TRUNCATE TABLE received_order           RESTART IDENTITY CASCADE;
TRUNCATE TABLE grn                      RESTART IDENTITY CASCADE;
TRUNCATE TABLE received_grn             RESTART IDENTITY CASCADE;

TRUNCATE TABLE assets                   RESTART IDENTITY CASCADE;
TRUNCATE TABLE org_assets               RESTART IDENTITY CASCADE;
TRUNCATE TABLE project_assets           RESTART IDENTITY CASCADE;

TRUNCATE TABLE vendors                  RESTART IDENTITY CASCADE;
TRUNCATE TABLE org_vendors              RESTART IDENTITY CASCADE;

TRUNCATE TABLE user_balance             RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_allowance           RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_expense             RESTART IDENTITY CASCADE;

TRUNCATE TABLE vendor_balance           RESTART IDENTITY CASCADE;
TRUNCATE TABLE vendor_payments          RESTART IDENTITY CASCADE;
TRUNCATE TABLE grn          RESTART IDENTITY CASCADE;